-- Actualizare categorii în limba română
UPDATE "Categories" SET "Name" = 'Tehnologie', "Slug" = 'tehnologie', "Description" = 'Cele mai recente tendințe tehnologice, inovații și dezvoltări din industrie' WHERE "Name" = 'Teknoloji';
UPDATE "Categories" SET "Name" = 'Inteligență Artificială', "Slug" = 'inteligenta-artificiala', "Description" = 'Tehnologii AI, machine learning și aplicații de deep learning' WHERE "Name" = 'Yapay Zeka';
UPDATE "Categories" SET "Name" = 'Tehnologie 5G', "Slug" = 'tehnologie-5g', "Description" = 'Rețele 5G, tehnologii mobile și comunicații de generație următoare' WHERE "Name" = '5G Teknolojisi';
UPDATE "Categories" SET "Name" = 'Dezvoltare Software', "Slug" = 'dezvoltare-software', "Description" = 'Limbaje de programare, arhitectură software, design patterns și best practices' WHERE "Name" = 'Yazılım Geliştirme';
UPDATE "Categories" SET "Name" = 'Cod Curat', "Slug" = 'cod-curat', "Description" = 'Principii de scriere a codului curat, refactorizare și calitate a codului' WHERE "Name" = 'Clean Code';
UPDATE "Categories" SET "Name" = 'Principii SOLID', "Slug" = 'principii-solid', "Description" = 'Principii SOLID și design orientat pe obiecte' WHERE "Name" = 'SOLID Prensipleri';
UPDATE "Categories" SET "Name" = 'Dezvoltare Web', "Slug" = 'dezvoltare-web', "Description" = 'Tehnologii de dezvoltare web frontend și backend, framework-uri și instrumente' WHERE "Name" = 'Web Development';
UPDATE "Categories" SET "Name" = 'Dezvoltare Frontend', "Slug" = 'dezvoltare-frontend', "Description" = 'HTML, CSS, JavaScript și framework-uri frontend moderne' WHERE "Name" = 'Frontend Development';
UPDATE "Categories" SET "Name" = 'Dezvoltare Backend', "Slug" = 'dezvoltare-backend', "Description" = 'Programare server-side, dezvoltare API și management baze de date' WHERE "Name" = 'Backend Development';
UPDATE "Categories" SET "Name" = 'Dezvoltare Full Stack', "Slug" = 'dezvoltare-full-stack', "Description" = 'Dezvoltare end-to-end a aplicațiilor web și deployment' WHERE "Name" = 'Full Stack Development';
UPDATE "Categories" SET "Name" = 'Dezvoltare Mobile', "Slug" = 'dezvoltare-mobile', "Description" = 'Ghiduri de dezvoltare aplicații mobile iOS, Android și cross-platform' WHERE "Name" = 'Mobile Development';
UPDATE "Categories" SET "Name" = 'Dezvoltare iOS', "Slug" = 'dezvoltare-ios', "Description" = 'Swift, SwiftUI și dezvoltare aplicații iOS' WHERE "Name" = 'iOS Development';
UPDATE "Categories" SET "Name" = 'Dezvoltare Android', "Slug" = 'dezvoltare-android', "Description" = 'Kotlin, Jetpack Compose și dezvoltare aplicații Android' WHERE "Name" = 'Android Development';
UPDATE "Categories" SET "Name" = 'Dezvoltare Cross-Platform', "Slug" = 'dezvoltare-cross-platform', "Description" = 'Dezvoltare cross-platform cu React Native, Flutter și Xamarin' WHERE "Name" = 'Cross-Platform Development';
UPDATE "Categories" SET "Name" = 'UI/UX Mobile', "Slug" = 'ui-ux-mobile', "Description" = 'Design interfață utilizator mobile și experiență utilizator' WHERE "Name" = 'Mobile UI/UX';
UPDATE "Categories" SET "Name" = 'Integrare Continuă', "Slug" = 'integrare-continua', "Description" = 'Pipeline-uri CI/CD, testare automată și procese de build' WHERE "Name" = 'Continuous Integration';
UPDATE "Categories" SET "Name" = 'Containerizare', "Slug" = 'containerizare', "Description" = 'Docker, Kubernetes și orchestrare containere' WHERE "Name" = 'Containerization';
UPDATE "Categories" SET "Name" = 'Monitorizare & Logging', "Slug" = 'monitorizare-logging', "Description" = 'Monitorizare aplicații, logging și observabilitate' WHERE "Name" = 'Monitoring & Logging';
UPDATE "Categories" SET "Name" = 'Servicii AWS', "Slug" = 'servicii-aws', "Description" = 'Amazon Web Services și soluții cloud computing' WHERE "Name" = 'AWS Services';
UPDATE "Categories" SET "Name" = 'Platformă Azure', "Slug" = 'platforma-azure', "Description" = 'Microsoft Azure și soluții cloud enterprise' WHERE "Name" = 'Azure Platform';
UPDATE "Categories" SET "Name" = 'Serverless Computing', "Slug" = 'serverless-computing', "Description" = 'Arhitectură serverless și function-as-a-service' WHERE "Name" = 'Serverless Computing';
UPDATE "Categories" SET "Name" = 'Baze de Date', "Slug" = 'baze-de-date', "Description" = 'SQL, NoSQL, design baze de date, optimizare și management' WHERE "Name" = 'Database';
UPDATE "Categories" SET "Name" = 'Baze de Date SQL', "Slug" = 'baze-de-date-sql', "Description" = 'Baze de date relaționale, SQL și proprietăți ACID' WHERE "Name" = 'SQL Databases';
UPDATE "Categories" SET "Name" = 'Baze de Date NoSQL', "Slug" = 'baze-de-date-nosql', "Description" = 'Baze de date non-relaționale și stocare distribuită a datelor' WHERE "Name" = 'NoSQL Databases';
UPDATE "Categories" SET "Name" = 'Design Baze de Date', "Slug" = 'design-baze-de-date', "Description" = 'Modelare baze de date, normalizare și design schemă' WHERE "Name" = 'Database Design';
UPDATE "Categories" SET "Name" = 'Performanță Baze de Date', "Slug" = 'performanta-baze-de-date', "Description" = 'Optimizare query-uri, indexare și tuning performanță' WHERE "Name" = 'Database Performance';
UPDATE "Categories" SET "Name" = 'Securitate', "Slug" = 'securitate', "Description" = 'Cybersecurity, securitate aplicații, penetration testing și best practices' WHERE "Name" = 'Security';
UPDATE "Categories" SET "Name" = 'Securitate Aplicații', "Slug" = 'securitate-aplicatii', "Description" = 'Securitate aplicații web, OWASP și secure coding' WHERE "Name" = 'Application Security';
UPDATE "Categories" SET "Name" = 'Securitate Rețea', "Slug" = 'securitate-retea', "Description" = 'Protecție rețea, firewall și detectare intruziuni' WHERE "Name" = 'Network Security';
UPDATE "Categories" SET "Name" = 'Criptografie', "Slug" = 'criptografie', "Description" = 'Criptare, hashing și protocoale criptografice' WHERE "Name" = 'Cryptography';
UPDATE "Categories" SET "Name" = 'Carieră', "Slug" = 'cariera', "Description" = 'Dezvoltare carieră, sfaturi interviu, dezvoltare profesională și networking' WHERE "Name" = 'Career';
UPDATE "Categories" SET "Name" = 'Interviuri de Angajare', "Slug" = 'interviuri-angajare', "Description" = 'Pregătire interviu, întrebări tehnice și strategii de interviu' WHERE "Name" = 'Job Interviews';
UPDATE "Categories" SET "Name" = 'Dezvoltare Competențe', "Slug" = 'dezvoltare-competente', "Description" = 'Dezvoltare competențe software și căi de învățare' WHERE "Name" = 'Skill Development';
UPDATE "Categories" SET "Name" = 'Freelancing', "Slug" = 'freelancing', "Description" = 'Dezvoltare software freelance și muncă la distanță' WHERE "Name" = 'Freelancing';

-- Actualizare titluri postări în limba română
UPDATE "Posts" SET "Title" = 'Tendințe Tehnologice în 2024 și Predicții pentru Viitor' WHERE "Title" LIKE '%2024%te Teknoloji Trendleri%';
UPDATE "Posts" SET "Title" = 'Quantum Computing: Puterea de Calcul a Viitorului' WHERE "Title" LIKE '%Quantum Computing: Geleceğin%';
UPDATE "Posts" SET "Title" = 'Metaverse: Ascensiunea Lumilor Virtuale' WHERE "Title" LIKE '%Metaverse: Sanal Dünyaların%';
UPDATE "Posts" SET "Title" = 'Edge Computing: Noua Față a Cloud Computing' WHERE "Title" LIKE '%Edge Computing: Bulut%';
UPDATE "Posts" SET "Title" = 'Green Tech: Soluții Tehnologice Sustenabile' WHERE "Title" LIKE '%Green Tech: Sürdürülebilir%';
UPDATE "Posts" SET "Title" = 'ChatGPT și Impactul AI Generativ în Lumea Afacerilor' WHERE "Title" LIKE '%ChatGPT ve Generative%';
UPDATE "Posts" SET "Title" = 'Computer Vision: Cum Computerele Învață să Vadă' WHERE "Title" LIKE '%Computer Vision: Görüntü%';
UPDATE "Posts" SET "Title" = 'Natural Language Processing: Înțelegerea Limbajului Uman' WHERE "Title" LIKE '%Natural Language Processing: Dil%';
UPDATE "Posts" SET "Title" = 'Etica AI: Provocări și Responsabilități' WHERE "Title" LIKE '%AI Ethics%';
UPDATE "Posts" SET "Title" = 'Deployment ML: De la Notebook la Producție' WHERE "Title" LIKE '%Machine Learning Model Deployment%';

-- Actualizare descrieri etichete în limba română
UPDATE "Tags" SET "Description" = 'Limbaj de programare modern de la Microsoft' WHERE "Name" = 'csharp';
UPDATE "Tags" SET "Description" = 'Platformă .NET și ecosistem' WHERE "Name" = 'dotnet';
UPDATE "Tags" SET "Description" = 'Limbajul de programare al web-ului' WHERE "Name" = 'javascript';
UPDATE "Tags" SET "Description" = 'Superset JavaScript cu tipuri' WHERE "Name" = 'typescript';
UPDATE "Tags" SET "Description" = 'Limbaj de programare versatil' WHERE "Name" = 'python';
UPDATE "Tags" SET "Description" = 'Framework web cross-platform' WHERE "Name" = 'aspnetcore';
UPDATE "Tags" SET "Description" = 'Librărie UI de la Facebook' WHERE "Name" = 'react';
UPDATE "Tags" SET "Description" = 'Framework complet de la Google' WHERE "Name" = 'angular';
UPDATE "Tags" SET "Description" = 'Framework JavaScript progresiv' WHERE "Name" = 'vue';
UPDATE "Tags" SET "Description" = 'Runtime JavaScript server-side' WHERE "Name" = 'nodejs';
UPDATE "Tags" SET "Description" = 'Platformă de containerizare' WHERE "Name" = 'docker';
UPDATE "Tags" SET "Description" = 'Platformă de orchestrare containere' WHERE "Name" = 'kubernetes';
UPDATE "Tags" SET "Description" = 'Platformă cloud Amazon Web Services' WHERE "Name" = 'aws';
UPDATE "Tags" SET "Description" = 'Platformă cloud Microsoft' WHERE "Name" = 'azure';
UPDATE "Tags" SET "Description" = 'Google Cloud Platform' WHERE "Name" = 'gcp';
UPDATE "Tags" SET "Description" = 'Arhitectură sistem distribuit' WHERE "Name" = 'microservices';
UPDATE "Tags" SET "Description" = 'Arhitectură computing serverless' WHERE "Name" = 'serverless';
UPDATE "Tags" SET "Description" = 'Application Programming Interface' WHERE "Name" = 'api';
UPDATE "Tags" SET "Description" = 'Limbaj de interogare pentru API-uri' WHERE "Name" = 'graphql';
UPDATE "Tags" SET "Description" = 'Stocare și management date' WHERE "Name" = 'database';
UPDATE "Tags" SET "Description" = 'Structured Query Language' WHERE "Name" = 'sql';
UPDATE "Tags" SET "Description" = 'Baze de date non-relaționale' WHERE "Name" = 'nosql';
UPDATE "Tags" SET "Description" = 'Bază de date orientată pe documente' WHERE "Name" = 'mongodb';
UPDATE "Tags" SET "Description" = 'Bază de date open source avansată' WHERE "Name" = 'postgresql';
UPDATE "Tags" SET "Description" = 'Stocare structuri de date în memorie' WHERE "Name" = 'redis';
UPDATE "Tags" SET "Description" = 'Motor de căutare și analiză' WHERE "Name" = 'elasticsearch';
UPDATE "Tags" SET "Description" = 'Software message broker' WHERE "Name" = 'rabbitmq';
UPDATE "Tags" SET "Description" = 'Platformă de streaming distribuit' WHERE "Name" = 'kafka';
UPDATE "Tags" SET "Description" = 'Librărie comunicare real-time' WHERE "Name" = 'signalr';
UPDATE "Tags" SET "Description" = 'Implementare protocol WebSocket' WHERE "Name" = 'websockets';
UPDATE "Tags" SET "Description" = 'Subset AI pentru recunoaștere pattern-uri' WHERE "Name" = 'machinelearning';
UPDATE "Tags" SET "Description" = 'Inteligență Artificială' WHERE "Name" = 'ai';
UPDATE "Tags" SET "Description" = 'Framework ML open source' WHERE "Name" = 'tensorflow';
UPDATE "Tags" SET "Description" = 'Framework deep learning' WHERE "Name" = 'pytorch';
UPDATE "Tags" SET "Description" = 'Tehnologie registru distribuit' WHERE "Name" = 'blockchain';
UPDATE "Tags" SET "Description" = 'Platformă blockchain' WHERE "Name" = 'ethereum';
UPDATE "Tags" SET "Description" = 'Criptomonedă și blockchain' WHERE "Name" = 'bitcoin';
UPDATE "Tags" SET "Description" = 'Tehnologii web descentralizat' WHERE "Name" = 'web3';
UPDATE "Tags" SET "Description" = 'Dezvoltare client-side' WHERE "Name" = 'frontend';
UPDATE "Tags" SET "Description" = 'HyperText Markup Language' WHERE "Name" = 'html';
UPDATE "Tags" SET "Description" = 'Cascading Style Sheets' WHERE "Name" = 'css';
UPDATE "Tags" SET "Description" = 'Framework CSS utility-first' WHERE "Name" = 'tailwindcss';
UPDATE "Tags" SET "Description" = 'Dezvoltare aplicații mobile' WHERE "Name" = 'mobile';
UPDATE "Tags" SET "Description" = 'Platformă mobilă Apple' WHERE "Name" = 'ios';
UPDATE "Tags" SET "Description" = 'Platformă mobilă Google' WHERE "Name" = 'android';
UPDATE "Tags" SET "Description" = 'Toolkit UI Google' WHERE "Name" = 'flutter';
UPDATE "Tags" SET "Description" = 'React pentru dezvoltare mobilă' WHERE "Name" = 'reactnative';
UPDATE "Tags" SET "Description" = 'Cybersecurity și protecție' WHERE "Name" = 'security';
UPDATE "Tags" SET "Description" = 'Metodologii de testare software' WHERE "Name" = 'testing';
UPDATE "Tags" SET "Description" = 'Integrare/Deployment Continuu' WHERE "Name" = 'cicd';
UPDATE "Tags" SET "Description" = 'Server de automatizare' WHERE "Name" = 'jenkins';
UPDATE "Tags" SET "Description" = 'Platformă DevOps' WHERE "Name" = 'gitlab';
UPDATE "Tags" SET "Description" = 'Platformă hosting cod' WHERE "Name" = 'github';
UPDATE "Tags" SET "Description" = 'Infrastructure as code' WHERE "Name" = 'terraform';
UPDATE "Tags" SET "Description" = 'Metodologie dezvoltare agile' WHERE "Name" = 'agile';
UPDATE "Tags" SET "Description" = 'Framework agile pentru echipe' WHERE "Name" = 'scrum';
UPDATE "Tags" SET "Description" = 'Management proiect vizual' WHERE "Name" = 'kanban';
UPDATE "Tags" SET "Description" = 'Dezvoltare profesională' WHERE "Name" = 'cariera';
UPDATE "Tags" SET "Description" = 'Pregătire interviu de angajare' WHERE "Name" = 'interviu';
UPDATE "Tags" SET "Description" = 'Networking profesional' WHERE "Name" = 'networking';
UPDATE "Tags" SET "Description" = 'Mentorat și îndrumare carieră' WHERE "Name" = 'mentorship';
UPDATE "Tags" SET "Description" = 'Ghiduri de învățare pas cu pas' WHERE "Name" = 'tutorial';
UPDATE "Tags" SET "Description" = 'Conținut pentru dezvoltatori începători' WHERE "Name" = 'incepatori';
UPDATE "Tags" SET "Description" = 'Best practices programare' WHERE "Name" = 'bestpractices';
UPDATE "Tags" SET "Description" = 'Tehnici de code review' WHERE "Name" = 'codereview';
